"""initial

Revision ID: 6a4920a1d526
Revises: 
Create Date: 2021-09-12 11:58:58.661958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4920a1d526'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('login', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
