"""initial

Revision ID: 6df9be169528
Revises: b82195732adf
Create Date: 2021-11-17 10:25:21.285010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df9be169528'
down_revision = 'b82195732adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_email', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirm_code', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_code')
    op.drop_column('user', 'confirmed_email')
    # ### end Alembic commands ###
