"""empty message

Revision ID: b82195732adf
Revises: 6a4920a1d526
Create Date: 2021-10-02 16:16:17.316542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82195732adf'
down_revision = '6a4920a1d526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_github_account', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_github_account')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
